SELECT T5.AI AS AUTHOR_ID, T5.AN AS AUTHOR_NAME, T5.CI AS CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM (
SELECT T4.BOOK_ID, T4.CATEGORY AS CI, T4.AUTHOR_ID AS AI, T4.AUTHOR_NAME AS AN, T4.PRICE AS PRICE, T3.SALES_DATE, T3.SALES
FROM BOOK_SALES AS T3
LEFT JOIN (
SELECT T1.BOOK_ID, T1.CATEGORY, T1.AUTHOR_ID, T2.AUTHOR_NAME, T1.PRICE
FROM BOOK AS T1
LEFT JOIN AUTHOR AS T2
ON T1.AUTHOR_ID = T2.AUTHOR_ID ) AS T4
ON T3.BOOK_ID = T4.BOOK_ID ) T5
WHERE SALES_DATE >= '2022-01-01'
  AND SALES_DATE < '2022-02-01'
GROUP BY T5.AI, T5.CI
ORDER BY AUTHOR_ID, CATEGORY DESC; 

