WITH RECURSIVE GENERATION_LOOP AS (
    
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT CHILD.ID, CHILD.PARENT_ID, PARENT.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA AS CHILD
    INNER JOIN GENERATION_LOOP AS PARENT
    ON CHILD.PARENT_ID = PARENT.ID )

SELECT ID
FROM GENERATION_LOOP
WHERE GENERATION = 3
ORDER BY ID;