SELECT T3.ITEM_ID, T3.ITEM_NAME,T3.RARITY
FROM ITEM_INFO AS T3
LEFT JOIN (
    SELECT DISTINCT T1.ITEM_ID AS NO_ID
    FROM ITEM_INFO AS T1
    INNER JOIN ITEM_TREE AS T2
    ON T1.ITEM_ID = T2.PARENT_ITEM_ID
    ) AS T4
ON T3.ITEM_ID = T4.NO_ID
WHERE T4.NO_ID IS NULL
ORDER BY T3.ITEM_ID DESC;

