-- 코드를 입력하세요
SELECT DISTINCT F.USER_ID, F.PRODUCT_ID
FROM ONLINE_SALE AS F
INNER JOIN ONLINE_SALE AS S
ON (F.USER_ID = S.USER_ID
    AND F.PRODUCT_ID = S.PRODUCT_ID)
    AND F.ONLINE_SALE_ID <> S.ONLINE_SALE_ID
ORDER BY USER_ID, PRODUCT_ID DESC;