SELECT T1.FOOD_TYPE, T2.REST_ID, T2.REST_NAME, T1.FAVORITES
FROM (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    ) AS T1
INNER JOIN REST_INFO AS T2
ON T1.FAVORITES = T2.FAVORITES AND T1.FOOD_TYPE = T2.FOOD_TYPE
ORDER BY T1.FOOD_TYPE DESC;
