SELECT T1.ID, 
        CASE
            WHEN T1.RANK_SIZE <= TOTAL_COUNT * 0.25 THEN 'CRITICAL'
            WHEN T1.RANK_SIZE <= TOTAL_COUNT * 0.50 THEN 'HIGH'
            WHEN T1.RANK_SIZE <= TOTAL_COUNT * 0.75 THEN 'MEDIUM'
            WHEN T1.RANK_SIZE <= TOTAL_COUNT THEN 'LOW'
            END AS COLONY_NAME
FROM (
SELECT ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANK_SIZE,
    ID, SIZE_OF_COLONY, COUNT(*) OVER () AS TOTAL_COUNT
FROM ECOLI_DATA
ORDER BY RANK_SIZE
    ) AS T1
ORDER BY ID;
    