SELECT T1.HISTORY_ID, T1.CAR_ID, T1.START_DATE, T1.END_DATE,
    CASE 
        WHEN T2.DIF >= 30 THEN '장기 대여'
        ELSE '단기 대여'
        END AS RENT_TYPE      
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS T1
INNER JOIN (
    SELECT HISTORY_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DIF
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    ) AS T2
ON T1.HISTORY_ID = T2.HISTORY_ID
WHERE YEAR(T1.START_DATE) = 2022 AND MONTH(T1.START_DATE) = 9
ORDER BY T1.HISTORY_ID DESC;