SELECT * 
FROM (
SELECT CAR_ID, 
    ROUND(AVG(DATEDIFF(END_DATE, START_DATE)) + 1, 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
    ) AS T1
WHERE T1.AVERAGE_DURATION >= 7
ORDER BY T1.AVERAGE_DURATION DESC, T1.CAR_ID DESC;
