SELECT T1.ROUTE, CONCAT(ROUND(T1.TOTAL_DISTANCE,1), 'km') AS TOTAL_DISTANCE, 
        CONCAT(ROUND(T1.TOTAL_DISTANCE / T1.COUNT,2), 'km') AS AVERAGE_DISTANCE
FROM (
    SELECT ROUTE, SUM(D_BETWEEN_DIST) AS TOTAL_DISTANCE, 
        COUNT(NO) AS COUNT
    FROM SUBWAY_DISTANCE
    GROUP BY ROUTE
    ) AS T1
ORDER BY T1.TOTAL_DISTANCE DESC;
