SELECT T1.CAR_TYPE, COUNT(T1.CAR_ID) AS CARS
FROM (
    SELECT *
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE OPTIONS LIKE '%통풍시트%' 
        OR OPTIONS LIKE '%열선시트%'
        OR OPTIONS LIKE '%가죽시트%'
        ) AS T1
GROUP BY T1.CAR_TYPE
ORDER BY T1.CAR_TYPE;

