SELECT COUNT(T3.ID) AS FISH_COUNT, T3.FISH_NAME
FROM (
    SELECT T1.ID, T2.FISH_NAME
    FROM FISH_INFO AS T1
    INNER JOIN FISH_NAME_INFO AS T2
    ON T1.FISH_TYPE = T2.FISH_TYPE
    ) AS T3
GROUP BY T3.FISH_NAME
ORDER BY COUNT(T3.ID) DESC;
