SELECT T1.QUARTER AS QUARTER, COUNT(T1.QUARTER)
FROM (
SELECT ID,
    CASE
        WHEN MONTH(DIFFERENTIATION_DATE) IN (1,2,3) THEN '1Q'
        WHEN MONTH(DIFFERENTIATION_DATE) IN (4,5,6) THEN '2Q'
        WHEN MONTH(DIFFERENTIATION_DATE) IN (7,8,9) THEN '3Q'
        WHEN MONTH(DIFFERENTIATION_DATE) IN (10,11,12) THEN '4Q'
        END AS QUARTER
FROM ECOLI_DATA
    ) AS T1
GROUP BY QUARTER
ORDER BY QUARTER;
