SELECT T2.ID AS ID, T2.NAME AS NAME, T2.HOST_ID AS HOST_ID
FROM (
SELECT HOST_ID
FROM PLACES
GROUP BY HOST_ID
HAVING COUNT(ID) >= 2
    ) AS T1
INNER JOIN PLACES AS T2
ON T1.HOST_ID = T2.HOST_ID
ORDER BY T2.ID;