SELECT T4.ID AS PRODUCT_ID, T3.PRODUCT_NAME AS PRODUCT_NAME, T4.SALES AS TOTAL_SALES
FROM FOOD_PRODUCT AS T3
INNER JOIN (
    SELECT T2.PRODUCT_ID AS ID, SUM(T1.PRICE * T2.AMOUNT) AS SALES
    FROM FOOD_PRODUCT AS T1
    INNER JOIN FOOD_ORDER AS T2
    ON T1.PRODUCT_ID = T2.PRODUCT_ID
    WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
    GROUP BY T2.PRODUCT_ID
    ) AS T4
ON T3.PRODUCT_ID = T4.ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;