SELECT T5.HISTORY_ID AS HISTORY_ID, T5.DAILY_FEE * T5.DIF * IFNULL((100 - T5.DISCOUNT_RATE)/100, 1) AS FEE
FROM (
SELECT T3.DAILY_FEE, T3.HISTORY_ID, T3.DIF, T4.DISCOUNT_RATE
FROM (
SELECT T1.CAR_TYPE, T1.DAILY_FEE, T2.HISTORY_ID, (DATEDIFF(END_DATE, START_DATE) +1) AS DIF,
    CASE 
        WHEN (DATEDIFF(END_DATE, START_DATE) +1) >= 7 AND (DATEDIFF(END_DATE, START_DATE) +1) < 30 THEN 7
        WHEN (DATEDIFF(END_DATE, START_DATE) +1) >= 30 AND (DATEDIFF(END_DATE, START_DATE) +1) < 90 THEN 30
        WHEN (DATEDIFF(END_DATE, START_DATE) +1) >= 90 THEN 90
        END AS LABEL
FROM CAR_RENTAL_COMPANY_CAR AS T1
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS T2
ON T1.CAR_ID = T2.CAR_ID
WHERE T1.CAR_TYPE = '트럭'
    ) AS T3
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS T4
ON T3.LABEL = CAST(REPLACE(T4.DURATION_TYPE, '일 이상', '') AS SIGNED) AND T3.CAR_TYPE = T4.CAR_TYPE
    ) AS T5
ORDER BY FEE DESC, HISTORY_ID DESC;

