SELECT T1.FLAVOR AS FLAVOR 
FROM FIRST_HALF AS T1
LEFT JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
    ) AS T2
ON T1.FLAVOR = T2.FLAVOR
ORDER BY (T1.TOTAL_ORDER + T2.TOTAL_ORDER) DESC
LIMIT 3;
