SELECT T4.APNT_NO AS APNT_NO, T3.PT_NAME AS PT_NAME, T3.PT_NO AS PT_NO, T4.MCDP AS MCDP_CD,
            T4.DR_NAME AS DR_NAME, T4.APNT_YMD AS APNT_YMD
FROM PATIENT AS T3
INNER JOIN (
    SELECT APNT_NO, T2.MCDP_CD AS MCDP, DR_NAME, APNT_YMD, PT_NO
    FROM DOCTOR AS T1
    INNER JOIN APPOINTMENT AS T2
    ON T1.DR_ID = T2.MDDR_ID
    WHERE APNT_CNCL_YN = 'N' AND T2.MCDP_CD = 'CS'
        ) AS T4
ON T3.PT_NO = T4.PT_NO
WHERE YEAR(T4.APNT_YMD) = 2022 AND MONTH(T4.APNT_YMD) = 4 AND DAY(T4.APNT_YMD) = 13
ORDER BY T4.APNT_YMD;
