SELECT T1.WRITER_ID AS USER_ID, T2.NICKNAME, T1.TOTAL_PRICE AS TOTAL_SALES
FROM (
SELECT WRITER_ID, SUM(PRICE) AS TOTAL_PRICE
FROM USED_GOODS_BOARD 
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING TOTAL_PRICE >= 700000
    ) AS T1
INNER JOIN USED_GOODS_USER AS T2
ON T1.WRITER_ID = T2.USER_ID
ORDER BY TOTAL_SALES;

