SELECT S.ITEM_ID, S.ITEM_NAME, S.RARITY
-- INFO 테이블에서 ITEM_ID를, ITEM_TREE 테이블에서 PARENT_ITEM_ID 가지고
FROM (
    SELECT * 
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
    ) AS I 
INNER JOIN ITEM_TREE AS T
ON I.ITEM_ID = T.PARENT_ITEM_ID
INNER JOIN ITEM_INFO AS S
ON T.ITEM_ID = S.ITEM_ID
ORDER BY S.ITEM_ID DESC;