SELECT MONTH(T2.START_DATE) AS MONTH, T2.CAR_ID, COUNT(*) AS RECORDS
FROM (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m')
          BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) AS T1
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS T2
ON T1.CAR_ID = T2.CAR_ID
WHERE DATE_FORMAT(T2.START_DATE, '%Y-%m')
      BETWEEN '2022-08' AND '2022-10'
GROUP BY MONTH(T2.START_DATE), T2.CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;