SELECT F.YEAR_1 AS YEAR, 
            (F.YEAR_MAX - S.SIZE_OF_COLONY) AS YEAR_DEV,
            S.ID
FROM ECOLI_DATA AS S 
INNER JOIN(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR_1, 
            MAX(SIZE_OF_COLONY) AS YEAR_MAX
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) AS F
ON F.YEAR_1 = YEAR(S.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV;