SELECT DISTINCT T1.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS T1
INNER JOIN (
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = '세단'
    ) AS T2
ON T1.CAR_ID = T2.CAR_ID
WHERE MONTH(T1.START_DATE) = 10
ORDER BY T2.CAR_ID DESC;