SELECT T3.ID, FN.FISH_NAME, T3.LENGTH
FROM FISH_INFO AS T3
    INNER JOIN (
    -- 두번째 조인 : 최대 길이와 물고기 테이블 연결 -> T4
    SELECT T1.ID, T1.FISH_TYPE AS TYPE, T1.LENGTH AS LENGTH_1
    FROM FISH_INFO AS T1
    INNER JOIN (
        -- 첫번째 조인 : 종류별 물고기 길이 최대 -> T2
        SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE
            ) AS T2
        ON T1.FISH_TYPE = T2.FISH_TYPE
    WHERE T1.LENGTH = T2.MAX_LENGTH
    ) AS T4
    ON T3.LENGTH = T4.LENGTH_1 AND T3.FISH_TYPE = T4.TYPE
-- 마지막 조인 : 물고기 이름 가져오기
INNER JOIN FISH_NAME_INFO AS FN
ON T3.FISH_TYPE = FN.FISH_TYPE
ORDER BY T3.ID;
    


