SELECT TOP.SCORE, INFO.EMP_NO, INFO.EMP_NAME, INFO.POSITION, INFO.EMAIL
FROM HR_EMPLOYEES AS INFO
INNER JOIN (
    SELECT SUM(SCORE) AS SCORE, T3.EMP_NO
    FROM (
        SELECT T1.EMP_NO, T1.EMP_NAME, T1.POSITION, T1.EMAIL, T2.SCORE
        FROM HR_EMPLOYEES AS T1 
        INNER JOIN HR_GRADE AS T2
        ON T1.EMP_NO = T2.EMP_NO
        WHERE T2.YEAR = 2022
        ) AS T3
    GROUP BY T3.EMP_NO
    ORDER BY SUM(SCORE) DESC
    LIMIT 1
    ) AS TOP
ON INFO.EMP_NO = TOP.EMP_NO;


    
