SELECT T2.DEPT_ID AS DEPT_ID, T1.DEPT_NAME_EN AS DEPT_NAME_EN, T2.TARGET AS AVG_SAL
FROM HR_DEPARTMENT AS T1
INNER JOIN (
    SELECT DEPT_ID, ROUND(AVG(SAL)) AS TARGET
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
    ) AS T2
ON T1.DEPT_ID = T2.DEPT_ID
ORDER BY AVG_SAL DESC;