SELECT T1.CATEGORY AS CATEGORY, SUM(T2.TOTAL) AS TOTAL_SALES
FROM BOOK AS T1
INNER JOIN (
SELECT BOOK_ID, SUM(SALES) AS TOTAL
FROM BOOK_SALES
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY BOOK_ID
    ) AS T2
ON T1.BOOK_ID = T2.BOOK_ID
GROUP BY T1.CATEGORY
ORDER BY T1.CATEGORY;
