SELECT T1.CATEGORY, T1.PRICE AS MAX_PRICE, T1.PRODUCT_NAME
FROM FOOD_PRODUCT AS T1
INNER JOIN (
SELECT CATEGORY AS TARGET_CATEGORY, MAX(PRICE) AS TARGET_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
    ) AS T2
ON T1.PRICE = T2.TARGET_PRICE AND T1.CATEGORY = T2.TARGET_CATEGORY
ORDER BY T1.PRICE DESC;