SELECT COUNT(FISH_TYPE2) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE2 AS FISH_TYPE
FROM (
    -- 그리고 평균 길이가 33 이상인 행 가져오고
    SELECT T2.FISH_TYPE1 AS FISH_TYPE2, T2.TARGET_LENGTH
    FROM (
        -- 두번째로, 물고기 종류대로 평균 길이를 구하고
        SELECT T1.FISH_TYPE AS FISH_TYPE1, AVG(REAL_LENGTH) AS TARGET_LENGTH
        FROM ( -- 일단, 물고기 길이가 NULL이면 10으로 세팅하고
            SELECT FISH_TYPE, IFNULL(LENGTH, 10) AS REAL_LENGTH
            FROM FISH_INFO
            ) AS T1
        GROUP BY T1.FISH_TYPE
        ) AS T2
    WHERE T2.TARGET_LENGTH >= 33
        ) AS T3 INNER JOIN FISH_INFO AS T4
ON T3.FISH_TYPE2 = T4.FISH_TYPE
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE;