SELECT T2.BOOK_ID AS BOOK_ID, T1.AUTHOR_NAME AS AUTHOR_NAME, T2.PUBLISHED_DATE AS PUBLISHED_DATE
FROM AUTHOR AS T1
    INNER JOIN (
    SELECT BOOK_ID, CATEGORY, AUTHOR_ID, PUBLISHED_DATE
    FROM BOOK
    WHERE CATEGORY = '경제'
    ) AS T2
ON T1.AUTHOR_ID = T2.AUTHOR_ID
ORDER BY PUBLISHED_DATE;