SELECT T1.PRICE_GROUP * 10000, COUNT(T1.PRODUCT_ID) AS PRODUCTS
FROM (
    SELECT PRODUCT_ID, FLOOR((PRICE / 10000)) AS PRICE_GROUP
    FROM PRODUCT
) AS T1
WHERE T1.PRICE_GROUP IS NOT NULL
GROUP BY T1.PRICE_GROUP
ORDER BY T1.PRICE_GROUP;